version: '3.7'

services:

  scaife-viewer:
    build:
      cache_from:
        - gcr.io/scaife-viewer/scaife-viewer-build:static-build
        - gcr.io/scaife-viewer/scaife-viewer-build:python-build
        - gcr.io/scaife-viewer/scaife-viewer-build:final-build
    image: gcr.io/scaife-viewer/scaife-viewer-build:final-build
